spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mms?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: admin123


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: psn.lxy.mms.POJO

logging:
  level:
    sql: debug
  group:
    sql: psn.lxy.mms.DAO

server:
  port: 8088
